### ISSUE TITLE
some files can not be opened

### ISSUE THREAD

**Issue by Kastet** [AnFengDe/AnFengDe_EPUB#1]
try this one which is ePub v3 : 

https://push.bigtincan.com/files/3ebea09a-44bd-11e2-9bec-4040eae9459f.epub

it does not show any errors in console.

**Comment by AnFengDe** [comment]
Thank you,being processed.

**Comment by AnFengDe** [comment]
We notice that there is a .plist file in your book. The book is not a standard EPub book, and we did not consider that, but now we've fixed the bug.
