### ISSUE TITLE
Has no method getAllBooks()

### ISSUE THREAD

**Issue by kuvark** [AnFengDe/AnFengDe_EPUB#10]
Hi, Thanks for your quick replies. 

I got this error. And when i click Add button on application there is nothing happen and console shown me this error.

Uncaught TypeError: Object [object Object] has no method 'getAllBooks' at file:///sdcard/epub/js/jindex.js:209

**Comment by AnFengDe** [comment]
Hi, 
I had tested our project, and it ran OK.
And we had discarded the add book function in recent versions.
The function exists in previous version.
You can get it by the command "git checkout 21bd864345b26" in your local repository.

And if the project can not run, you can refer to this issuse:#8.

**Comment by distjoy** [comment]
Hi,
After compiling and testing the samples app, the bookshelf shows no book and all the three buttons (back, add, edit) are unresponsive. Kindly help out
