### ISSUE TITLE
About library theme

### ISSUE THREAD

**Issue by kuvark** [AnFengDe/AnFengDe_EPUB#11]
How can i change librar theme? In raw folder you got some html codes, but when i change them with mine, application doesnt work.

**Comment by AnFengDe** [comment]
Please change value, not html element id or name.

**Comment by kuvark** [comment]
Is there any way to call just EpubViewer component? I really dont want to use your html book library and i m ready to pay for google ads. I created an html5 gui and i want to use your Android.showBook(bookPath); function from my webview. Is that possible? Thank you so much for your kind replies.

**Comment by AnFengDe** [comment]
Sorry, you can't use your html5 in our project. You can only modify the value of our html, js and css to customize the interface.
But you can use our EPub SDK, the parsing part, to develop your Reader and use your html interface.
And we will give your the interface document of the EPub SDK after getting your payment.
