### ISSUE TITLE
In Android CallEPubUI sample it is impossible to turn pages

### ISSUE THREAD

**Issue by xmblpb** [AnFengDe/AnFengDe_EPUB#16]
I compile and run latest CallEPubUI sample. It successfully open the book, but it is impossible to turn pages. When i swipe screen page stop on half first and half second pages.

**Comment by AnFengDe** [comment]
Thank you for run and test our sample.
Yes, the page turn function is simple in our sdk, only show sliding effect, not curl flip effect.
we will add this feature, thank you very much.

**Comment by xmblpb** [comment]
Thanks for fast response, but seems i describe problem wrong.
I completely unable to navigate between pages, i stuck on first and between first and second pages.
I unable to get second, third and next pages, navigation is just not work,

**Comment by AnFengDe** [comment]
Hi, xmblpb, the CallEPubUI sample project be test pass over iPhone 5.0(and higher) and Android 2.3(or higher).
Please tell us your runtime enviroment: OS, simulator/device, let us check it.

**Comment by xmblpb** [comment]
I run the sample on Android 4.1.9 device 480x800

**Comment by AnFengDe** [comment]
Hi, we have no Android 4.1.9 device(We can not find it in android official site.). And we had tested our sample project on Android 4.1.2 and 4.2.2, it ran OK.
