### ISSUE TITLE
EPUB SDK Example Not working

### ISSUE THREAD

**Issue by devapalanisamy** [AnFengDe/AnFengDe_EPUB#17]
Hi ,

I am not able to see contents of any chapter when I run IOS EPUB SDK example. If I click any chapter , It is not navigating to contents of the chapter. I have attached the screenshot of the issue.

![screen shot 2013-10-16 at 8 49 27 am](https://f.cloud.github.com/assets/5352735/1339734/7a9d34ae-3612-11e3-81be-a07c1b80e030.png)

Thanks,
Deva

**Comment by AnFengDe** [comment]
Hi, devapalanisamy 
https://github.com/AnFengDe/EPUB_SDK/tree/master/ios/EPUB_SDK_Example just a SDK sample, only for open book, parse book metadata, not for show epub book content.

try this https://github.com/AnFengDe/EPUB_SDK/tree/master/ios/UI_Example
