### ISSUE TITLE
CallEPUBUI  sample Can't import books on Android 4.2.2

### ISSUE THREAD

**Issue by songpyong** [AnFengDe/AnFengDe_EPUB#18]
Hello, When i open CallEPUBUI Sample on Android 4.2.2 
then appear  "import error!!" message.
it seems to can't load libepubjni.so on Android 4.2.2.

Please, Help.

**Comment by AnFengDe** [comment]
It time at weekend, I will check it and reply to you later.

**Comment by AnFengDe** [comment]
Hi, songpyong
I have test CallEPUBUI sample again, but everything is ok.

Can you tell us more detail of your dev enviroment ? 
Thank you.

**Comment by songpyong** [comment]
I try to run CallEPUBUI sample on Android 4.2.2 Emulator and Galaxy S4 LTE-A(this is only in korea).
And show up "import error!"

I Got Error Message Like Below In Android 4.2.2 Emulator.

10-21 01:51:37.496: D/dalvikvm(1801): Trying to load lib /data/app-lib/com.anfengde.ui.call-2/libepubjni.so 0xb2eda910
10-21 01:51:37.496: D/dalvikvm(1801): Added shared lib /data/app-lib/com.anfengde.ui.call-2/libepubjni.so 0xb2eda910
10-21 01:51:37.515: D/dalvikvm(1801): No JNI_OnLoad found in /data/app-lib/com.anfengde.ui.call-2/libepubjni.so 0xb2eda910, skipping init

Please Check It.

And another error report is on Android Gingerbread , Reflowable Type ePub file is rendering incorrectly.
the first page is show up , but from next pages are all blank.

**Comment by songpyong** [comment]
hello, another bug report is it can't increase or decrease font size when open Reflowable ePub file.

**Comment by AnFengDe** [comment]
Sorry for reply later. 
I was busy working on the job at hand to deal with this issue.

**Comment by AnFengDe** [comment]
font size zoom out and in is ok.
I have run CallEpubUI project in emulator which created for Galaxy successful.

It is strange for us, please pull repo and check again.

![zoomin](https://f.cloud.github.com/assets/1912973/1397652/b9a1b664-3c8b-11e3-9520-9096a46491c6.png)
![zoomout](https://f.cloud.github.com/assets/1912973/1397653/b9a1df54-3c8b-11e3-9d60-853267680991.png)

**Comment by songpyong** [comment]
I have no idea why you can load on Android 4.2.2.
and i think depend on epub file. i also test on your sample epub file. everything is ok.
but on my epub3 file, bookmark, font size increase or decrease functions does not working.

**Comment by AnFengDe** [comment]
Oh....., I see.
Can you send your epub file to me for check again?

**Comment by AnnaPhan** [comment]
Hello,
When I CallEPUBUI Sample on Android 4.0.3, I also get an error message:
01-23 17:05:20.259: D/dalvikvm(20163): Trying to load lib /data/data/com.anfengde.epub_sdk_example/lib/libepubjni.so 0x40d59268
01-23 17:05:20.259: D/dalvikvm(20163): Added shared lib /data/data/com.anfengde.epub_sdk_example/lib/libepubjni.so 0x40d59268
01-23 17:05:20.259: D/dalvikvm(20163): No JNI_OnLoad found in /data/data/com.anfengde.epub_sdk_example/lib/libepubjni.so 0x40d59268, skipping init

Please Help

**Comment by AnFengDe** [comment]
The function "JNI_OnLoad" is not essential. 
 D/dalvikvm(20163) .... D means debug info, not error.
Did you see epub sdk example activity show? Try click button for use it.

:->  If sdk example running before ui example, try copy android/lib/EPUB_UI/libs folder to this project.

**Comment by AnnaPhan** [comment]
Thanks,
I have view two examples on http://epub.anfengde.com/examples/ . I run EPUB SDK example, I run test is OK , but only GetMetadata button click have error:
01-24 15:52:49.753: A/libc(15132): Fatal signal 11 (SIGSEGV) at 0x000001c1 (code=1)

I run the EPUB UI Example and then I see the debug:
01-23 17:05:20.259: D/dalvikvm(20163): Trying to load lib /data/data/com.anfengde.epub_sdk_example/lib/libepubjni.so 0x40d59268
01-23 17:05:20.259: D/dalvikvm(20163): Added shared lib /data/data/com.anfengde.epub_sdk_example/lib/libepubjni.so 0x40d59268
01-23 17:05:20.259: D/dalvikvm(20163): No JNI_OnLoad found in /data/data/com.anfengde.epub_sdk_example/lib/libepubjni.so 0x40d59268, skipping init

And the program don't run anymore.

Please help!

**Comment by AnFengDe** [comment]
Sorry, AnnaPhan, We are in Chinese holiday（Spring festival）, we will deal this issue in 15 days.

We tested all of the simulator between android 2.2-4.4, without you on the problem, I think it might still question the environment settings, if convenient, please tell us more details, if you use the example of testing outside books, please send us for test.

**Comment by AnnaPhan** [comment]
Ok, I think have error when config lib so not found some function ( at here is JNI_OnLoad) ...

**Comment by AnFengDe** [comment]
Hi, AnnaPhan
I am back from holiday. Please re-pull or clone from repo and try it again, we update source recently.

**Comment by AnnaPhan** [comment]
Thank you,
I have run the example successfully. It's amazing! Now I will learn how to use.
