### ISSUE TITLE
Where is the src directory in EPUB_UI for android?

### ISSUE THREAD

**Issue by miyang** [AnFengDe/AnFengDe_EPUB#2]
I pull the code and find  EPUB_UI doesn't has the src dir, and the CallEPubUI can not work, pls help me to make it work, thanks a lot.

**Comment by AnFengDe** [comment]
Thank you! The src directory isn't necessary. If your eclipse can't compile the EPUB_UI, you can create a empty src in it. Please tell us the detail error.
