### ISSUE TITLE
Sampel project does not works  

### ISSUE THREAD

**Issue by Yedi07** [AnFengDe/AnFengDe_EPUB#21]
Hi,

I keep getting a "error code is -29" everytime i try to use the sample project.

What is going wrong?

int ret = [EPubONI openEPubBook:epubFilePath];
ret is always = 0

I checked the filepath and file, both are valid.

There's been the same issue seven month ago, but closed by owner without comment.

What can I do to solve?

Thx

**Comment by AnFengDe** [comment]
Hi, Yedl07
You call open book function twice.
Error code -29 means the first openbook calling just running for extract & parse epub book in background.
You got ret value after first calling, check it.

**Comment by Yedi07** [comment]
Hi AnFengDe,

thx for the quick response!

I am running EPUB_SDK_Example as it is.
To ensure that I don't call double, I set breakpoints on every appearance of openEPubBook: it is one hit and immediately returning 0.
I also made sure to really press the button only once ;)

**Comment by Yedi07** [comment]
I found the problem:
The Button < initEpubEnv> in the view was hidden.
Pulling all Buttons down a little in IB revealed the missing button and using it solved the problem.
