### ISSUE TITLE
A problem from building CallEPubUI

### ISSUE THREAD

**Issue by Kerry50407** [AnFengDe/AnFengDe_EPUB#22]
Hello! I followed
"http://epub.anfengde.com/2012/08/09/getting-started-with-epub-ui-component/"
this page to build an android app..
But after I finished the steps,I could't see this...
![screen shot 2012-12-20 at 1 15 38 pm](https://f.cloud.github.com/assets/6603554/2097332/2c516b82-8f16-11e3-8af9-06a11c68c471.png)

Instead, my screen is like this..
![screenshot_2014-02-06-18-07-58](https://f.cloud.github.com/assets/6603554/2097374/d1641e44-8f16-11e3-95f0-e79690f22fa6.png)

and can't add books on the bookshelf

Can you tell me how to add books and where should I put the ".epub" file? 
Thanks!

**Comment by AnFengDe** [comment]
Hi, Kerry50407 
Thanks for report issue.
I have check repo again, and found we did not push assets folder. We will fix it later.

You can create assets folder in project folder, and mkdir books folder inside, then put your epub file in it, the epub ui will add it in shelf automatically.

Thanks again.

**Comment by Kerry50407** [comment]
Hi AnFengDe!
Thank you for qiuck response.

I have tried to create assets folder and put epub file in it.
But there still no any book on the bookshelf.

I didn't know much about these lines..
Are there some things I didn't notice?
![11](https://f.cloud.github.com/assets/6603554/2105932/4e1d0cbc-8f98-11e3-9f78-34cb84d13b3b.jpg)

Or 
I should write something to replace
"Constants.CACHE_PAHT"    in    "bookView.setPath(Constants.CACHE_PAHT);"?

Thanks for your patience!!

**Comment by AnFengDe** [comment]
Hi, Kerry50407
Please pull new version for try.

Thanks for report issue.

**Comment by Kerry50407** [comment]
OK~ I will try it later.
Thanks!!

**Comment by Kerry50407** [comment]
It works!
That is a wonderful project~

Thank you for all your assistance!! :+1:
