### ISSUE TITLE
Exit Book Reader without entering Anfengde Book Shelf

### ISSUE THREAD

**Issue by joaodallarosa** [AnFengDe/AnFengDe_EPUB#3]
Hello,

I'm testing a android application and I'm having this problem that while I'm in book reading I would like to press the Back button and the application return to my own Book Shelf without openning the Anfengde Book Shelf. I have already tryied to force open an Activity with onBackPressed() function but it does not work. How can I do that?

Thanks for your support!

**Comment by AnFengDe** [comment]
Hi,
Sorry for that. Our application just comes back to Anfengde Book Shelf when pressing the Back button. It cann't open your Bookshelf or Activity.
But you can customize our Bookshelf by modifying our HTML files.

Thanks for your message.
