### ISSUE TITLE
Arabic Problem

### ISSUE THREAD

**Issue by wessam** [AnFengDe/AnFengDe_EPUB#5]
I have a problem in reading arabic epub files because of the direction of language and the handling of the ciew .
So, my question is can i edit in the library source code.

**Comment by AnFengDe** [comment]
Our application supports arabic epub files.
You can just edit the html source code.
![Screen Shot 2013-01-31 at 10 14 25 AM](https://f.cloud.github.com/assets/1912973/113321/30b7c85e-6b4c-11e2-802f-91093e3068c5.png)

**Comment by wessam** [comment]
it's good on iphone by default but on android it's .
could you tell me what the html source code.or where i can find
![1-31-2013 9-30-28 AM](https://f.cloud.github.com/assets/306629/113792/25547c10-6b78-11e2-9906-fbbecde88f21.png)

**Comment by AnFengDe** [comment]
The picture above is the effect in android. Are there any problems? We don't understand Arabic.

**Comment by wessam** [comment]
the problem is the arabic direction is from tight to left but here is from left to right which is not readable and characters are separated not connected to each other like photo you added

**Comment by AnFengDe** [comment]
Can you give us your book for testing?
Let us to test it on Android and iOS.
Our email:afd@anfengde.com

This is the effect in iBooks.
![IMG_0094](https://f.cloud.github.com/assets/1912973/113918/809a3c6e-6b81-11e2-8a46-8b672f38dba0.PNG)

**Comment by wessam** [comment]
thnx a lot ,it's worked on a real device.
 i need to ask if i can get jar files source code or not even for fees

**Comment by wessam** [comment]
i asked my last question because i need to integrate arabic reader with my android application
