### ISSUE TITLE
https://epub-samples.googlecode.com/files/GhV-oeb-page-20121015.epub application crashed immediately each time I tried to import 

### ISSUE THREAD

**Issue by AnFengDe** [AnFengDe/AnFengDe_EPUB#6]
Hello guys!

My name is Lukasz and I am a head of of development team that is responsible for delivery of internal EPUB mobile reader. I made research on the web and found your SDK, and I have to say that you done great job!

Unfortunately, when I compiled your CallEPubUI project for Android and tried to import EPUB file from following link:
https://epub-samples.googlecode.com/files/GhV-oeb-page-20121015.epub
application crashed immediately each time I tried to import. 

Last LOGCAT messages:
03-14 09:00:49.785: D/GestureDetector(18640): [Surface Touch Event] mSweepDown False, mLRSDCnt : -1 mTouchCnt : 4 mFalseSizeCnt:0
03-14 09:00:49.790: V/webview(18640):  singleCursorHandlerTouchEvent -getEditableSupport  FASLE 
03-14 09:00:50.165: A/libc(18640): @@@ ABORTING: INVALID HEAP ADDRESS IN dlfree addr=0x5a29df40
03-14 09:00:50.165: A/libc(18640): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 18668 (WebViewCoreThre)

Tested on Samsung Galaxy Note 2, Android 4.1.2. Code was cloned from your GitHub. 

Could you help me in tracking the problem down?

Looking forward for your reply.

Best regards,
Łukasz Czarnecki

**Comment by AnFengDe** [comment]
This bug was fixed. You can pull the new version. Thanks for you report.

**Comment by wangtianlang0912** [comment]
hello ，I have  a same problem about this , I use this Animation method,below android  4.0 version is worked well,but above 4.0... 

this code is :

```
animation=AnimationUtils.loadAnimation(mcontext,animId); 
```

 the bug is:
D/GestureDetector(2888): [Surface Touch Event] mSweepDown False, mLRSDCnt : -1 mTouchCnt : 2 mFalseSizeCnt:0

could you give me some help? I want to know how I can solve it ? 

please reply to wangtianlang0912@gmail.com Thank you very much!

**Comment by AnFengDe** [comment]
Hi, wangtianlang0912
Is your problem open same book? 
GhV-oeb-page-20121015.epub miss some content which epub standard needed, we fixed exception handle for this bug.

Can you paste more code for we debug it ?

**Comment by wangtianlang0912** [comment]
hi， thanks for you reply.my code is following:

// private void setAnimation(final View view,int animId,final boolean isShow){
// 
// Animation animation=AnimationUtils.loadAnimation(mcontext,animId);
// animation.setAnimationListener(new AnimationListener() {
// @Override
// public void onAnimationStart(Animation animation) {
// // TODO Auto-generated method stub
// Log.e("onAnimationStart","onAnimationStart");
// view.setVisibility(isShow?View.VISIBLE:View.GONE);
// 
// }
// @Override
// public void onAnimationRepeat(Animation animation) {
// // TODO Auto-generated method stub
// Log.e("onAnimationRepeat","onAnimationRepeat");
// }
// @Override
// public void onAnimationEnd(Animation animation) {
// // TODO Auto-generated method stub
// Log.e("onAnimationEnd","onAnimationEnd");
// view.clearAnimation(); 
// }
// });
// view.startAnimation(animation); 
// }

I want to show an effect about a view  visible or unvisible .  when I debug this code, I found that "onAnimationStart(Animation animation)" can work well  ,
but the another two methods have no effect.  so what I want to show is ineffective.   the anim xml likes this:

picshow_top_disappear.xml 

<?xml version="1.0" encoding="UTF-8"?>
<set android:interpolator="@android:anim/accelerate_interpolator"
xmlns:android="http://schemas.android.com/apk/res/android">
<translate android:duration="500" android:fromYDelta="0.0" android:toYDelta="-100.0%p" />
</set>

picshow_top_show.xml 
<?xml version="1.0" encoding="UTF-8"?>
<set android:interpolator="@android:anim/decelerate_interpolator"
xmlns:android="http://schemas.android.com/apk/res/android">
<translate android:duration="500" android:fromYDelta="-100.0%p" android:toYDelta="0.0" />
</set>

From: AnFengDe
Date: 2013-04-27 21:00
To: AnFengDe/EPUB_SDK
CC: wangtianlang0912
Subject: Re: [EPUB_SDK] https://epub-samples.googlecode.com/files/GhV-oeb-page-20121015.epub application crashed immediately each time I tried to import (#6)
Hi, wangtianlang0912
Is your problem open same book? 
GhV-oeb-page-20121015.epub miss some content which epub standard needed, we fixed exception handle for this bug.
Can you paste more code for we debug it ?

**Comment by AnFengDe** [comment]
I tested the code in our project and it ran OK. I don't know why it happened to you.

**Comment by wangtianlang0912** [comment]
oh,thank you very much,I have to have a try on other machines.thanks for your help.

AnFengDe notifications@github.com编写：
