### ISSUE TITLE
Error when loading Android Example on Mac Eclipse

### ISSUE THREAD

**Issue by walter17** [AnFengDe/AnFengDe_EPUB#7]
Hi, i'm having trouble running the example project files on Eclipse Android SDK on Mac. Can anyone help me on this, I'll appreciate any help. Thanks in advance. Here's the error

![Screen Shot 2013-04-17 at 11 35 24 AM](https://f.cloud.github.com/assets/4167949/389528/ecce8402-a70f-11e2-877f-faba0114efea.png)

**Comment by AnFengDe** [comment]
Hi, 
Please make sure that you have set the sdcard size. 
![Screen Shot 2013-04-17 at 4 27 24 PM](https://f.cloud.github.com/assets/1912973/390270/e6d4d58c-a738-11e2-973b-51c82c1708af.png)
Thanks for you comment.
