### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.anfengde.epub.ui.BookView" 

### ISSUE THREAD

**Issue by kuvark** [AnFengDe/AnFengDe_EPUB#8]
When i run the ui sample, all the time after splash screen it closes.

**Comment by AnFengDe** [comment]
Hi, 
Thanks!
We had noticed this bug. And it was cause by the updating of eclipse. And we had updated our project, you can download it.
If the bug happens again, you can fixed it like this:
1. in the eclipse, right on the EPUB_UI project --> click Properties -->click Java Build Path -->click Order and Export, and then select Android Private Libraries.
2. right on the CallEPubUI project--> click Properties -->click Java Build Path -->click Order and Export, and then select Android Private Libraries.
3. clean the projects.

![screen shot 2013-06-12 at 5 03 24 pm](https://f.cloud.github.com/assets/1912973/641739/178393da-d33f-11e2-8f54-a2935d35e1f5.png)

**Comment by lequysang** [comment]
Thanks!
