### ISSUE TITLE
jdb.js not found

### ISSUE THREAD

**Issue by kuvark** [AnFengDe/AnFengDe_EPUB#9]
Hi, I run your ui component but nothing happened. and i looked the code, add button is not working and jdb.js is not found. where can i get this jdb.js

**Comment by AnFengDe** [comment]
Hi, you can find the jdb.js in the EPUB_SDK/android/lib/EPUB_UI/res/raw floder.
And if the project can not run, you can refer to this issuse:https://github.com/AnFengDe/EPUB_SDK/issues/8.
